sonar.projectKey=RAESystem_lilrae
sonar.organization=raesystem
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=600

sonar.sources=src,tools
sonar.tests=tests
sonar.python.version=3.11,3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=\
  **/__pycache__/**,\
  **/.venv/**,\
  **/build/**,\
  **/dist/**,\
  **/*.egg-info/**
