from __future__ import annotations

import pytest

import tools.check_pr_title as pr_title
from tools.check_pr_title import validate_title


@pytest.mark.parametrize(
    "title",
    [
        "chore: establish repository baseline",
        "feat(cli): add lifecycle diagnostics",
        "fix: reject private RAES imports",
    ],
)
def test_valid_conventional_titles(title: str) -> None:
    assert validate_title(title) is None


@pytest.mark.parametrize(
    "title",
    [
        "Establish repository baseline",
        "feat: Add lifecycle diagnostics",
        "codex: establish repository baseline",
        "feat: generated by AI",
    ],
)
def test_invalid_or_attributed_titles(title: str) -> None:
    assert validate_title(title) is not None


def test_pr_title_cli(
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    monkeypatch.setattr("sys.argv", ["check-pr-title", "chore: establish baseline"])
    assert pr_title.main() == 0
    assert "OK" in capsys.readouterr().out

    monkeypatch.setattr("sys.argv", ["check-pr-title", "invalid title"])
    with pytest.raises(SystemExit) as exit_info:
        pr_title.main()
    assert exit_info.value.code == 2
